[hugoVersion]
extended = false
min = "0.80.0"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "documentation"
target = "content/gohugo/internals"


[[mounts]]
source = "data"
target = "data"
