[hugoVersion]
extended = false
min = "0.80.0"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/internals.json"

[[mounts]]
source = "data"
target = "data"
