[dnb.netlification]
upgradeInsecureRequests = true
# mode - defines output formats
# netlify = Netlify
# github = Github Pages (tbd)
# gitlab = Gitlab Pages (tbd)
# cloudflare = Cloudflare Pages (tbd)
mode = "netlify"
# extensions (tbd)
# extensions = ["youtube", "cloudflare.insights"]
# ignored header fields
# @todo move to netlify specific settings
ignored_headers = [
  "Accept-Ranges",
  "Age",
  "Allow",
  "Alt-Svc",
  "Connection",
  "Content-Encoding",
  "Content-Length",
  "Content-Range",
  "Date",
  "Location",
  "Server",
  "Set-Cookie",
  "Trailer",
  "Transfer-Encoding",
  "Upgrade",
]
ignored_headers_info = "https://docs.netlify.com/routing/headers/#limitations"

[dnb.netlification.defaults]
# default value of "Accept-Encoding: gzip, deflate, br"
acceptEncoding = "gzip, deflate, br"
# default value of "Cache-Control: public, max-age={{- $cacheSeconds -}}, immutable"
cacheControl = "public, max-age=%d, immutable"

# the default minimal CSP
[dnb.netlification.csp]
default-src = ["'self'"]

# set caching duration, default is 1 year
[dnb.netlification.cache.duration]
years = 1
months = 0
days = 0

#[headers]
#for = "/pwa/reset"
#[headers.rules]
## https://developer.chrome.com/docs/workbox/remove-buggy-service-workers/
## https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data
#Clear-Site-Data = ["cache", "cookies", "storage", "executionContexts"]

# netlify specific settings
[dnb.netlification.netlify]
#cms = true

# github specific settings
[dnb.netlification.github]

# gitlab specific settings
[dnb.netlification.gitlab]

# cloudflare specific settings
[dnb.netlification.cloudflare]

[[dnb.hooks.items.netlification.body-end]]
file = "body-end"
cached = false
