[dnb.netlification]
upgradeInsecureRequests = true
# modes available
# netlify = Netlify
# github = Github Pages
# gitlab = Gitlab Pages
# cloudflare = Cloudflare Pages
mode = "netlify"
# extensions = ["youtube", "cloudflare.insights"]

[dnb.netlification.defaults]
# default value of "Accept-Encoding: gzip, deflate, br"
acceptEncoding = "gzip, deflate, br"
# default value of "Cache-Control: public, max-age={{- $cacheSeconds -}}, immutable"
cacheControl = "public, max-age=%s, immutable"

# the default minimal CSP
[dnb.netlification.csp]
defaultSrc = ["'self'"]

# set caching duration, default is 1 year
[dnb.netlification.cache.duration]
years = 1
months = 0
days = 0

#[headers]
#for = "/pwa/reset"
#[headers.rules]
## https://developer.chrome.com/docs/workbox/remove-buggy-service-workers/
## https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data
#Clear-Site-Data = ["cache", "cookies", "storage", "executionContexts"]

# netlify specific settings
[dnb.netlification.netlify]
#cms = true

# github specific settings
[dnb.netlification.github]

# gitlab specific settings
[dnb.netlification.gitlab]

# cloudflare specific settings
[dnb.netlification.cloudflare]
