[[module.mounts]]
source = "content/posts"
target = "content/posts"

[[mounts]]
source = "package.json"
target = "assets/dnb/iliad.json"

[[mounts]]
source = "documentation"
target = "content/gohugo/iliad"
