################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/aesop/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/auditor/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/debug/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/devtools/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/errors/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/feeds/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/functions/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/giscus/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/head/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/headerimage/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/hooks/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/icons/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/iliad/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/internals/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/modder/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/netlification/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/opensearch/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/pictures/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/publisher/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/pwa/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/renderhooks/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/robots/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/schema/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/security/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/seo/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/shortcodes/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/sitemap/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/social/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/modules/youtube/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"
