[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/head.json"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/hooks"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
