[dnb.head]
charset = "utf-8"
colorschemeOrder = "dark light"
nobase = true
separator = " | "
viewport = "width=device-width, initial-scale=1"

[dnb.head.fediverse]
creator = ''

[dnb.head.styles]
# external, postcss, tailwind
entrypoint = "scss/style.scss"
method = "postcss"

[dnb.head.styles.sassOptions]
# sass options, see https://gohugo.io/functions/css/sass/#options
enableSourceMap = true
ignoreErrors = ["dnb-sample-error"]
includePaths = ["node_modules/"]
outputStyle = "compressed"
targetPath = "assets/theme.css"

[dnb.head.styles.postcssOptions]
# postcss options, see https://gohugo.io/functions/css/postcss/#options
# config = ""
# noMap = false
# inlineImports = false
# skipInlineImportsNotFound = false
# for use without a config file, set the following:
# https://gohugo.io/functions/css/postcss/#no-configuration-file

[dnb.head.styles.tailwindOptions]
# tailwind options, see https://gohugo.io/functions/css/tailwindcss/#options
# minify = false
# optimize = false
# inlineImports = false
# skipInlineImportsNotFound = false

[dnb.head.styles.externalOptions]
target = "/styles.css"

# [dnb.head.verification]
# google = ""
# yandex = ""
# bing = ""
# alexa = ""
# pinterest = ""
# norton = ""
