[dnb.head]
charset = "utf-8"
viewport = "width=device-width, initial-scale=1"
nobase = true
separator = " | "
colorschemeOrder = "dark light"

[dnb.head.styles]
entrypoint = "scss/style.scss"
method = "postcss"

[dnb.head.styles.options]
outputType = "preload"           # one of direct or preload
outputStyle = "compressed"
targetPath = "assets/theme.css"
enableSourceMap = true
includePaths = ["node_modules/"]

ignoreErrors = ["dnb-sample-error"]
