[hugoVersion]
extended = true
min = "0.84.4"

[[mounts]]
source = 'layouts'
target = 'layouts'

[[mounts]]
source = 'assets'
target = 'assets'

[[mounts]]
source = "documentation"
target = "content/gohugo/modder"
