[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = 'assets'
target = 'assets'

[[mounts]]
source = "package.json"
target = "data/dnb/modder/modder.json"

[[mounts]]
source = 'layouts'
target = 'layouts'
