[hugoVersion]
extended = true
min = "0.56.0"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "package.json"
target = "assets/dnb/hooks.json"

[[mounts]]
source = "documentation"
target = "content/gohugo/hooks"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
disable = false
ignoreConfig = false
ignoreImports = false
