[hugoVersion]
extended = false
min = "0.56.0"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/hooks.json"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
disable = false
ignoreConfig = false
ignoreImports = false
