[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/headerimage.json"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"
