[module]

[module.hugoVersion]
extended = false
min = "0.84.4"

[[module.mounts]]
source = "content"
target = "content"

[[mounts]]
source = "package.json"
target = "assets/dnb/errors.json"


[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "layouts"
target = "layouts"
