################################################################################
# configuration
################################################################################
[hugoVersion]
extended = false
min = "0.56.0"

[[mounts]]
source = "layouts/"
target = "layouts/"

[[mounts]]
source = "data/"
target = "data/"

[[mounts]]
source = "package.json"
target = "assets/dnb/security.json"

[[mounts]]
source = "documentation"
target = "content/gohugo/security"


# [[mounts]]
# source = "content/dnb/privacy/"
# target = "content/dnb/privacy/"
