################################################################################
# configuration
################################################################################
[hugoVersion]
extended = false
min = "0.56.0"

[[mounts]]
source = "layouts/"
target = "layouts/"

[[mounts]]
source = "data/"
target = "data/"

[[mounts]]
source = "package.json"
target = "assets/dnb/security.json"
