[hugoVersion]
extended = true
min = "0.91.0"

[[mounts]]
source = "assets/js/debug.js"
target = "assets/js/debug.js"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "documentation"
target = "content/gohugo/functions"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"
