################################################################################
# configuration
################################################################################
[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "documentation"
target = "content/gohugo/seo"


[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-modules/modules/head"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-modules/modules/robots"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-modules/modules/sitemap"
