[hugoVersion]
extended = false
min = "0.84.0"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/icons.json"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/twbs/icons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "icons"
target = "assets/icons/bootstrap-icons"
