[hugoVersion]
extended = true
min = "0.84.0"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/davidsneighbour/hugo-modules/modules/hooks'

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/davidsneighbour/hugo-modules/modules/debug'

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/davidsneighbour/hugo-modules/modules/functions'

[[imports]]
path = "github.com/twbs/icons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "icons"
target = "assets/icons/bootstrap-icons"

[[imports]]
path = "github.com/tailwindlabs/heroicons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "optimized/outline"
target = "assets/icons/heroicons/24/outline"

[[imports.mounts]]
source = "optimized/solid"
target = "assets/icons/heroicons/24/solid"

[[imports]]
path = "github.com/tabler/tabler-icons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "src/_icons"
target = "assets/icons/tabler-icons"
