[hugoVersion]
extended = false
min = "0.120.1"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "assets/scss/_debugprint.scss"
target = "assets/scss/_debugprint.scss"

[[mounts]]
source = "assets/js/debug.js"
target = "assets/js/debug.js"

[[mounts]]
source = "static/assets/js/"
target = "assets/dnb/debug/files/"

[[mounts]]
source = "content"
target = "content"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/hooks"
