[hugoVersion]
extended = false
min = "0.92.0"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "assets/scss/_debugprint.scss"
target = "assets/scss/_debugprint.scss"

[[mounts]]
source = "content"
target = "content"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/hooks"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
