[dnb.debug]
loglink = "https://dnbql.netlify.app/log"
namespace = "dnb"
debuglevel = 8
development = true

[dnb.debug.formats]
datetime = ""
datetime_extended = ""

[dnb.debug.config.plugins.js]
imports = ["import 'debug';"] # es6, in flux

[dnb.debug.config.plugins.scss]
imports = ["scss/_debugprint.scss"]

[[dnb.hooks.items.debug.head-post-css]]
file = "debugprint-head-post-css"
cached = true

[[dnb.hooks.items.debug.footer-widgets-end]]
file = "debugprint-footer-widgets-end"
cached = false
