#!/bin/bash
# v2024.08.04.01

# get the current path
CURPATH="$(pwd -P)"
MODULE_NAME=$(basename "$CURPATH")

# shellcheck disable=SC1091
source "${CURPATH}/bin/repo/release/common"

set -e

check_required_tools curl git npm hugo
load_env_vars "${CURPATH}/../../.env"

# Get current version from package.json
RELEASE=$(node -pe 'require("./package.json")["version"]')
TAGNAME="modules/${MODULE_NAME}/v${RELEASE}"

# create a release on GitHub
GITHUB_REPO=https://github.com/${GITHUB_REPOSLUG}

# push release to GitHub
git push origin main --follow-tags
git push origin --tags

# open release for editing
code changes.md
xdg-open "$GITHUB_REPO/releases/edit/$TAGNAME" &>/dev/null
