################################################################################
# configuration
################################################################################
[module.hugoVersion]
extended = false
min = "0.84.4"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "documentation"
target = "content/gohugo/schema"
