################################################################################
# configuration
################################################################################
[module.hugoVersion]
extended = false
min = "0.84.4"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/schema.json"
