[hugoVersion]
extended = false
min = "0.56.0"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/youtube.json"
