[dnb.feeds]
limit = 10
summary = true
drafts = false

[dnb.feeds.webfeed]
# webfeed protocol
logo = ""
accentColor = ""
coverImage = ""
icon = ""

[dnb.feeds.atom]
limit = 10
summary = true
drafts = false

[dnb.feeds.rss]
limit = 10
summary = true
drafts = false

[dnb.feeds.json]
limit = 10
summary = true
drafts = false
