[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "package.json"
target = "assets/dnb/giscus.json"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"
