[hugoVersion]
extended = true
min = "0.84.4"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "package.json"
target = "assets/dnb/giscus.json"

[[mounts]]
source = "documentation"
target = "content/gohugo/giscus"


[[mounts]]
source = "layouts"
target = "layouts"
