[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/pwa.json"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"
