[hugoVersion]
extended = false
min = "0.84.0"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/social.json"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/icons"
disable = false
ignoreConfig = false
ignoreImports = false
