[hugoVersion]
extended = true
min = "0.56.0"

[[mounts]]
source = "assets/libs/lite-vimeo/lite-vimeo.js"
target = "assets/libs/lite-vimeo/lite-vimeo.js"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "package.json"
target = "assets/dnb/shortcodes.json"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"
