[dnb.forms.contactform]
id = "contactform"
labelling = "i18n"  # either inline or i18n
groups = true       # fields will have multiple groups that will result in groupstyle
groupstyle = "grid" # single, tabs, grid, fieldsets

[dnb.forms.contactform.attributes]
data-netlify = "true"
netlify-honeypot = "%random%"
class = "mb-6"

[[dnb.forms.contactform.fields.1]]
name = "shortcodes.form.fieldnames.name"
label = "shortcodes.form.name"
type = "text"
required = true

[[dnb.forms.contactform.fields.1]]
name = "shortcodes.form.fieldnames.subject"
label = "shortcodes.form.subject"
type = "text"
required = true

[[dnb.forms.contactform.fields.1]]
name = "shortcodes.form.fieldnames.email"
label = "shortcodes.form.email"
type = "email"
required = true

[[dnb.forms.contactform.fields.1]]
type = "special"
html = "<div data-netlify-recaptcha=\"true\"></div>"

[[dnb.forms.contactform.fields.1]]
type = "invisible"
name = "%random%"

[[dnb.forms.contactform.fields.2]]
name = "shortcodes.form.fieldnames.message"
label = "shortcodes.form.message"
type = "textarea"
required = true

[dnb.forms.contactform.fields.2.options]
rows = 8

[[dnb.forms.contactform.buttons]]
type = "submit"
name = "shortcodes.form.fieldnames.submit"
label = "shortcodes.form.submit"
class = "btn btn-primary"
